.PHONY: all run_all clean

all: run_all

run_all: run_programa1 run_programa2 run_programa3 run_programa4 run_programa5 run_programa6 run_programa7 run_programa8 run_programa9 run_programa10

run_programa1:
	swipl -s ../src/programa1.pl -g main -t halt

run_programa2:
	swipl -s ../src/programa2.pl -g main -t halt

# ... Repite para los demás programas hasta run_programa10

clean:
	@echo "Limpiando archivos generados..."
	# Añade comandos de limpieza si es necesario
